-- GENERATED by scripts/write_event_log_vector_test.dart from fixtures/chain/. Do not edit: change a
-- vector there, then re-run the script. test/event_log_vectors_sql_test.dart fails on any difference.
--
-- pgTAP tests for #40 criteria 8 and 9: #28's chain vectors, inserted into the event log, hash back
-- to each event's recorded hash when SHA-256 is recomputed over the row's stored canonical text. If
-- the canonical column were jsonb, the text read back would be jsonb's own serialisation and no
-- hash would match. Run with `supabase test db` against the local stack; the whole file is one
-- transaction and rolls back.
--
-- Vectors reuse ULIDs across files (an altered or re-linked event keeps its ULID), so each vector
-- goes into an empty log inside a subtransaction that is rolled back once its hashes are read.

begin;
create extension if not exists pgtap with schema extensions;
select plan(10);

insert into public.club (id, name) values ('00000000-0000-0000-0000-000000000c01', 'Hoover (fixture)');
select public.create_event('00000000-0000-0000-0000-000000000c01', 'Club night', date '2026-09-27', 'gull-1234',
                           '00000000-0000-0000-0000-000000000e01');

-- Inserts one vector's events as the table owner, the role #48's append_event will run as. Each
-- text goes in as a literal, so a change to the canonical column's type still takes the insert and
-- shows up as a hash that no longer matches. Returns how many rows the log then held, and how many
-- of them hash to the recorded hash of the vector event with the same ULID.
create function pg_temp.check_vector(p_vector jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_event  constant uuid := '00000000-0000-0000-0000-000000000e01';
  v_text   text;
  v_stored bigint;
  v_match  bigint;
begin
  begin
    for v_text in select e ->> 'canonical' from jsonb_array_elements(p_vector -> 'events') e loop
      execute format('insert into public.event_log (event_id, canonical) values (%L, %L)', v_event, v_text);
    end loop;
    select count(*),
           count(*) filter (where encode(sha256(convert_to(l.canonical::text, 'UTF8')), 'hex') = r.hash)
      into v_stored, v_match
      from public.event_log l
      left join (select e ->> 'hash' as hash, (e ->> 'canonical')::jsonb ->> 'ulid' as ulid
                   from jsonb_array_elements(p_vector -> 'events') e) r on r.ulid = l.ulid
     where l.event_id = v_event;
    raise exception using errcode = 'PCV01', message = 'check_vector: roll this vector back';
  exception when sqlstate 'PCV01' then
    null;
  end;
  return jsonb_build_object('stored', v_stored, 'hash_matches', v_match);
end;
$$;

-- fixtures/chain/broken-first-link.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-first-link",
  "description": "Seq 1's previous hash is not the genesis value; the rest link to it correctly.",
  "events": [
    {
      "hash": "a1774f1fa120f7b79bc19c94821416e08b64ec48681ec776931186cbd468d010",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "da4e0b90604142472cd9021ba2ef870a9b8f3a0075fabef0ad593571496447b1",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"a1774f1fa120f7b79bc19c94821416e08b64ec48681ec776931186cbd468d010\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "33fe2a05fc050d176ba7f71b6cdc7965ec3b01ddaa436d17f962931161dda799",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"da4e0b90604142472cd9021ba2ef870a9b8f3a0075fabef0ad593571496447b1\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "8119bac6cdc4756d12bf23c89a0ce3401722681474b50e728d6e4afcfc28a8c5",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"33fe2a05fc050d176ba7f71b6cdc7965ec3b01ddaa436d17f962931161dda799\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "bcda35f7c12c943bbaa2bbf4dda163b7c1b5222a845fb09f9e42f93f9110f89b",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"8119bac6cdc4756d12bf23c89a0ce3401722681474b50e728d6e4afcfc28a8c5\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "1c21fd30319eec9bd101ba798557888e28092bcaf348266bf2dc48e270975391",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"bcda35f7c12c943bbaa2bbf4dda163b7c1b5222a845fb09f9e42f93f9110f89b\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 1,
      "at_ulid": "01J8Z0E0000000000000000001"
    }
  }
}
$vector$),
          '{"stored": 6, "hash_matches": 6}'::jsonb,
          'broken-first-link: all 6 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-fork.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-fork",
  "description": "Two events hold seq 3, both linking to seq 2, as when a phone restored from a backup appends again. Verifiers read equal numbers in ULID order and name the later ULID.",
  "events": [
    {
      "hash": "93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "5e142bcfb6352c2b2737c5772d7819ef16df9d7d7c10701b75ca1cb82af4083f",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190007000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Restored from a backup\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000007\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 3,
      "at_ulid": "01J8Z0E0000000000000000007"
    }
  }
}
$vector$),
          '{"stored": 4, "hash_matches": 4}'::jsonb,
          'broken-fork: all 4 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-payload.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-payload",
  "description": "One byte of seq 4's payload was altered (sail 12345 became 12346) after seq 5 linked to it. Seq 5's link no longer holds, so the chain breaks at seq 5, after seq 4: either one could be the altered event.",
  "events": [
    {
      "hash": "93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "b2520ef21040c3c6749e5b237481828edccc9039e78f70907348d8bee9f38f25",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12346\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ac145bb6cad3c1a7fc409cc02e1257e4dfca1c97020e18810b1f4e9b87912c98\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "1f6b0c611fbc0f7ba58ddc2ee4e277a0588e2066e111651221fd6ade8820448f",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 5,
      "at_ulid": "01J8Z0E0000000000000000005",
      "after_seq": 4
    }
  }
}
$vector$),
          '{"stored": 6, "hash_matches": 6}'::jsonb,
          'broken-payload: all 6 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-relinked-start.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-relinked-start",
  "description": "Seq 1 and 2 were removed and seq 3 re-linked to genesis, with the rest re-linked after it. Only a first event starts from genesis.",
  "events": [
    {
      "hash": "c1ae57b3a21f04467d0f7d3fd572d09d8e1d7ca5703737bcbc678ac2751c6b5e",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "dd9b42e4b25de98bd3fa7566b203da5b05afd6d9253424d169cb216e1125342f",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"c1ae57b3a21f04467d0f7d3fd572d09d8e1d7ca5703737bcbc678ac2751c6b5e\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "49249a787b74ef4ec1cbeea6f80af32692c8fe643c8ebf250de511f3aeaf126a",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"dd9b42e4b25de98bd3fa7566b203da5b05afd6d9253424d169cb216e1125342f\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "570ead68b214ea938adae636da01711e334d7612b164dfcedd21807220104885",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"49249a787b74ef4ec1cbeea6f80af32692c8fe643c8ebf250de511f3aeaf126a\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 3,
      "at_ulid": "01J8Z0E0000000000000000003"
    }
  }
}
$vector$),
          '{"stored": 4, "hash_matches": 4}'::jsonb,
          'broken-relinked-start: all 4 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-relinked.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-relinked",
  "description": "Seq 3 was removed and seq 4 re-linked to seq 2, with seq 5 and 6 re-linked after it. Seq 4 links straight across the missing number, which a genuine chain never does.",
  "events": [
    {
      "hash": "93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "46360628330405b8625f2498c4c6a354a5831849652a39b5c0a5578a2d41acef",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "8c91aa3d7d15476a6779097bf0a68cd258a8e973a40708cd67978f9231a067b6",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"46360628330405b8625f2498c4c6a354a5831849652a39b5c0a5578a2d41acef\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "e756809e5f0c9e838804a8b0633957fce35c453dd3cb49cb8cc6420189b9852e",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"8c91aa3d7d15476a6779097bf0a68cd258a8e973a40708cd67978f9231a067b6\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 4,
      "at_ulid": "01J8Z0E0000000000000000004",
      "after_seq": 2
    }
  }
}
$vector$),
          '{"stored": 5, "hash_matches": 5}'::jsonb,
          'broken-relinked: all 5 events stored, each hashing to its recorded hash');

-- fixtures/chain/gapped-middle.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "gapped-middle",
  "description": "Seq 3 and 4 have not arrived yet. Seq 5 still links to seq 4, which this verifier has not seen, so the gap cannot be checked and is not tampering.",
  "events": [
    {
      "hash": "93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ac145bb6cad3c1a7fc409cc02e1257e4dfca1c97020e18810b1f4e9b87912c98\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "1f6b0c611fbc0f7ba58ddc2ee4e277a0588e2066e111651221fd6ade8820448f",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "gapped"
    }
  }
}
$vector$),
          '{"stored": 4, "hash_matches": 4}'::jsonb,
          'gapped-middle: all 4 events stored, each hashing to its recorded hash');

-- fixtures/chain/gapped-start.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "gapped-start",
  "description": "A far mark catching up: seq 1 to 3 have not arrived, and seq 4 links to a seq 3 not yet seen.",
  "events": [
    {
      "hash": "ac145bb6cad3c1a7fc409cc02e1257e4dfca1c97020e18810b1f4e9b87912c98",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ac145bb6cad3c1a7fc409cc02e1257e4dfca1c97020e18810b1f4e9b87912c98\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "1f6b0c611fbc0f7ba58ddc2ee4e277a0588e2066e111651221fd6ade8820448f",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "gapped"
    }
  }
}
$vector$),
          '{"stored": 3, "hash_matches": 3}'::jsonb,
          'gapped-start: all 3 events stored, each hashing to its recorded hash');

-- fixtures/chain/handoff.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "handoff",
  "description": "Device A's first three events and device B's two: a phone handed over mid-race is a new device with its own chain, from genesis. Each device is verified on its own.",
  "events": [
    {
      "hash": "93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "745e5d810a64aea2367fd694c0bca130bd4ff773eb00832cec604755fc1ca033",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000002\",\"device_ts\":1727190011000,\"gps\":{\"accuracy_m\":3.5,\"lat\":33.4105,\"lon\":-86.8201},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"mark_boat\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000011\"}"
    },
    {
      "hash": "853869b7b31ff7484bf89a4c84b48384abd7de813daafe8ea13217744a5475f7",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000002\",\"device_ts\":1727190012000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000011\",\"sail\":\"4471\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"745e5d810a64aea2367fd694c0bca130bd4ff773eb00832cec604755fc1ca033\",\"role\":\"mark_boat\",\"seq\":2,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000012\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "intact"
    },
    "01J8Z0D0000000000000000002": {
      "verdict": "intact"
    }
  }
}
$vector$),
          '{"stored": 5, "hash_matches": 5}'::jsonb,
          'handoff: all 5 events stored, each hashing to its recorded hash');

-- fixtures/chain/intact.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "intact",
  "description": "Device A's whole day, seq 1 to 6, every link as written.",
  "events": [
    {
      "hash": "93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"93322f023cbc83656fe652883020940402d8508b2e6fcaa0835251db33f56e95\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"e259853094cbe74261840aa9119c5c9fcaf93b7cc1f791653b89a288c2211af4\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "ac145bb6cad3c1a7fc409cc02e1257e4dfca1c97020e18810b1f4e9b87912c98",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"aa3c9f0af1520c519516b25674f8bef6173ff524e67a94688924e3ad85e4a94f\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7",
      "canonical": "{\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ac145bb6cad3c1a7fc409cc02e1257e4dfca1c97020e18810b1f4e9b87912c98\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "1f6b0c611fbc0f7ba58ddc2ee4e277a0588e2066e111651221fd6ade8820448f",
      "canonical": "{\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"a033ec286076563b31b09c011858efdb2b2dcb99c1652ce9eabfb663f20244f7\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "intact"
    }
  }
}
$vector$),
          '{"stored": 6, "hash_matches": 6}'::jsonb,
          'intact: all 6 events stored, each hashing to its recorded hash');

select is((select count(*) from public.event_log), 0::bigint, 'every vector was rolled back, so each went into an empty log');

select * from finish();
rollback;
