-- GENERATED by scripts/write_event_log_vector_test.dart from fixtures/chain/. Do not edit: change a
-- vector there, then re-run the script. test/event_log_vectors_sql_test.dart fails on any difference.
--
-- pgTAP tests for #40 criteria 8 and 9: #28's chain vectors, inserted into the event log, hash back
-- to each event's recorded hash when SHA-256 is recomputed over the row's stored canonical text. If
-- the canonical column were jsonb, the text read back would be jsonb's own serialisation and no
-- hash would match. Run with `supabase test db` against the local stack; the whole file is one
-- transaction and rolls back.
--
-- Vectors reuse ULIDs across files (an altered or re-linked event keeps its ULID), so each vector
-- goes into an empty log inside a subtransaction that is rolled back once its hashes are read.

begin;
create extension if not exists pgtap with schema extensions;
select plan(10);

insert into public.club (id, name) values ('00000000-0000-0000-0000-000000000c01', 'Hoover (fixture)');
select public.create_event('00000000-0000-0000-0000-000000000c01', 'Club night', date '2026-09-27',
                           '00000000-0000-0000-0000-000000000e01');

-- Inserts one vector's events as the table owner, the role #48's append_event will run as. Each
-- text goes in as a literal, so a change to the canonical column's type still takes the insert and
-- shows up as a hash that no longer matches. Returns how many rows the log then held, and how many
-- of them hash to the recorded hash of the vector event with the same ULID.
create function pg_temp.check_vector(p_vector jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_event  constant uuid := '00000000-0000-0000-0000-000000000e01';
  v_text   text;
  v_stored bigint;
  v_match  bigint;
begin
  begin
    for v_text in select e ->> 'canonical' from jsonb_array_elements(p_vector -> 'events') e loop
      execute format('insert into public.event_log (event_id, canonical) values (%L, %L)', v_event, v_text);
    end loop;
    select count(*),
           count(*) filter (where encode(sha256(convert_to(l.canonical::text, 'UTF8')), 'hex') = r.hash)
      into v_stored, v_match
      from public.event_log l
      left join (select e ->> 'hash' as hash, (e ->> 'canonical')::jsonb ->> 'ulid' as ulid
                   from jsonb_array_elements(p_vector -> 'events') e) r on r.ulid = l.ulid
     where l.event_id = v_event;
    raise exception using errcode = 'PCV01', message = 'check_vector: roll this vector back';
  exception when sqlstate 'PCV01' then
    null;
  end;
  return jsonb_build_object('stored', v_stored, 'hash_matches', v_match);
end;
$$;

-- fixtures/chain/broken-first-link.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-first-link",
  "description": "Seq 1's previous hash is not the genesis value; the rest link to it correctly.",
  "events": [
    {
      "hash": "fcae2be770d5d84379b61e2f29dab70682682e4391a4ca897eb16a90d06d36d2",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "ccb9bb84e5eafbb9e8ccecd3ec1db8b46c0b3b2e70286ad127dd7be37d2e59d3",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"fcae2be770d5d84379b61e2f29dab70682682e4391a4ca897eb16a90d06d36d2\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "a4f426aa08a78ac0743531a64d5bf3b77767d60ad4190e906c2bf9566af63dae",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"ccb9bb84e5eafbb9e8ccecd3ec1db8b46c0b3b2e70286ad127dd7be37d2e59d3\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "da9f677a8fd1f0ab848b2874e716a693a58332e1b74cf50e4e72a0ea9600595d",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"a4f426aa08a78ac0743531a64d5bf3b77767d60ad4190e906c2bf9566af63dae\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "22fbbe51d00eb9c70594cc3e98db1fa0a55ef1f859f8e53f75ddd7f6b62e7ea1",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"da9f677a8fd1f0ab848b2874e716a693a58332e1b74cf50e4e72a0ea9600595d\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "033d813576ceaf155c154fc4a92314d47ead345b2336a0d04d09085a53b5b0d2",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"22fbbe51d00eb9c70594cc3e98db1fa0a55ef1f859f8e53f75ddd7f6b62e7ea1\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 1,
      "at_ulid": "01J8Z0E0000000000000000001"
    }
  }
}
$vector$),
          '{"stored": 6, "hash_matches": 6}'::jsonb,
          'broken-first-link: all 6 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-fork.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-fork",
  "description": "Two events hold seq 3, both linking to seq 2, as when a phone restored from a backup appends again. Verifiers read equal numbers in ULID order and name the later ULID.",
  "events": [
    {
      "hash": "7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "45b79a6bd5844d3af660b7b3e8a79b4ae64a6541dfdad3f7c281e9fac3fef1b9",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190007000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Restored from a backup\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000007\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 3,
      "at_ulid": "01J8Z0E0000000000000000007"
    }
  }
}
$vector$),
          '{"stored": 4, "hash_matches": 4}'::jsonb,
          'broken-fork: all 4 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-payload.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-payload",
  "description": "One byte of seq 4's payload was altered (sail 12345 became 12346) after seq 5 linked to it. Seq 5's link no longer holds, so the chain breaks at seq 5, after seq 4: either one could be the altered event.",
  "events": [
    {
      "hash": "7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "604357e5002dbde8ee0465a4e6d8aaed1acce1427303bcac8ede4cf23a7b5002",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12346\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"fcdfc8a416c0687959e2f814a46448b904b8586258f53a2e5671571577841a62\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "49e0441befdddcbf81458741bdd8552abe6ada968e26f9e3c8207e244642dc57",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 5,
      "at_ulid": "01J8Z0E0000000000000000005",
      "after_seq": 4
    }
  }
}
$vector$),
          '{"stored": 6, "hash_matches": 6}'::jsonb,
          'broken-payload: all 6 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-relinked-start.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-relinked-start",
  "description": "Seq 1 and 2 were removed and seq 3 re-linked to genesis, with the rest re-linked after it. Only a first event starts from genesis.",
  "events": [
    {
      "hash": "0326d4a74fcc2ee5dc81280d573f401081d4a8dadfffd5b1fd6f8f5acd04ed3f",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "af99b35237d6e9fe2cc7d36c67eb59ed62a898ace7123dda437fa9897f0260c0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0326d4a74fcc2ee5dc81280d573f401081d4a8dadfffd5b1fd6f8f5acd04ed3f\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "794e6fae2e61bffe3d7e19d844b735c127bc2f90cf7faa0ce62638782cc1be2f",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"af99b35237d6e9fe2cc7d36c67eb59ed62a898ace7123dda437fa9897f0260c0\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "e67c57763362485085f2f8ed9160dc62780896ac9720dec94321b709fc89699c",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"794e6fae2e61bffe3d7e19d844b735c127bc2f90cf7faa0ce62638782cc1be2f\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 3,
      "at_ulid": "01J8Z0E0000000000000000003"
    }
  }
}
$vector$),
          '{"stored": 4, "hash_matches": 4}'::jsonb,
          'broken-relinked-start: all 4 events stored, each hashing to its recorded hash');

-- fixtures/chain/broken-relinked.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "broken-relinked",
  "description": "Seq 3 was removed and seq 4 re-linked to seq 2, with seq 5 and 6 re-linked after it. Seq 4 links straight across the missing number, which a genuine chain never does.",
  "events": [
    {
      "hash": "7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "2fb4212f82cc1eb722e865c738a1bb0b32ea72f43b9766374adfd45e250fdd95",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "910edf84766ee2fe0d91f699ad1108a383ae61207bc0e8d38a3ba5dd9d48d5d7",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"2fb4212f82cc1eb722e865c738a1bb0b32ea72f43b9766374adfd45e250fdd95\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "a77334502c3006e0f35dbd75326af7f07fa24f3cd354100e118961d2ad029556",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"910edf84766ee2fe0d91f699ad1108a383ae61207bc0e8d38a3ba5dd9d48d5d7\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "broken",
      "at_seq": 4,
      "at_ulid": "01J8Z0E0000000000000000004",
      "after_seq": 2
    }
  }
}
$vector$),
          '{"stored": 5, "hash_matches": 5}'::jsonb,
          'broken-relinked: all 5 events stored, each hashing to its recorded hash');

-- fixtures/chain/gapped-middle.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "gapped-middle",
  "description": "Seq 3 and 4 have not arrived yet. Seq 5 still links to seq 4, which this verifier has not seen, so the gap cannot be checked and is not tampering.",
  "events": [
    {
      "hash": "7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"fcdfc8a416c0687959e2f814a46448b904b8586258f53a2e5671571577841a62\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "49e0441befdddcbf81458741bdd8552abe6ada968e26f9e3c8207e244642dc57",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "gapped"
    }
  }
}
$vector$),
          '{"stored": 4, "hash_matches": 4}'::jsonb,
          'gapped-middle: all 4 events stored, each hashing to its recorded hash');

-- fixtures/chain/gapped-start.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "gapped-start",
  "description": "A far mark catching up: seq 1 to 3 have not arrived, and seq 4 links to a seq 3 not yet seen.",
  "events": [
    {
      "hash": "fcdfc8a416c0687959e2f814a46448b904b8586258f53a2e5671571577841a62",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"fcdfc8a416c0687959e2f814a46448b904b8586258f53a2e5671571577841a62\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "49e0441befdddcbf81458741bdd8552abe6ada968e26f9e3c8207e244642dc57",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "gapped"
    }
  }
}
$vector$),
          '{"stored": 3, "hash_matches": 3}'::jsonb,
          'gapped-start: all 3 events stored, each hashing to its recorded hash');

-- fixtures/chain/handoff.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "handoff",
  "description": "Device A's first three events and device B's two: a phone handed over mid-race is a new device with its own chain, from genesis. Each device is verified on its own.",
  "events": [
    {
      "hash": "7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "45b90a247fa59af721f3ca1c5313fe345df09dd9abfd166e6704657df4bfef5f",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000b1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000002\",\"device_ts\":1727190011000,\"gps\":{\"accuracy_m\":3.5,\"lat\":33.4105,\"lon\":-86.8201},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"mark_boat\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000011\"}"
    },
    {
      "hash": "5c190096b7c5b3b0eaa08c276644387423cc6e565b21cafbe81f1441dcfe6081",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000b1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000002\",\"device_ts\":1727190012000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000011\",\"sail\":\"4471\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"45b90a247fa59af721f3ca1c5313fe345df09dd9abfd166e6704657df4bfef5f\",\"role\":\"mark_boat\",\"seq\":2,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000012\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "intact"
    },
    "01J8Z0D0000000000000000002": {
      "verdict": "intact"
    }
  }
}
$vector$),
          '{"stored": 5, "hash_matches": 5}'::jsonb,
          'handoff: all 5 events stored, each hashing to its recorded hash');

-- fixtures/chain/intact.json
select is(pg_temp.check_vector($vector${
  "format": "pro-companion-chain-vector/1",
  "name": "intact",
  "description": "Device A's whole day, seq 1 to 6, every link as written.",
  "events": [
    {
      "hash": "7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190001000,\"gps\":null,\"kind\":\"fleet.defined\",\"payload\":{\"class\":\"ILCA 7\",\"name\":\"Lasers\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"role\":\"overall_pro\",\"seq\":1,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000001\"}"
    },
    {
      "hash": "90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190002000,\"gps\":null,\"kind\":\"start\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"7b89d856d0e8552fa0365dfcc34f5b40d0c3049c14432f3ac94cf4851c2555e0\",\"role\":\"overall_pro\",\"seq\":2,\"source\":\"race-timer\",\"ulid\":\"01J8Z0E0000000000000000002\"}"
    },
    {
      "hash": "0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190003000,\"gps\":{\"accuracy_m\":5,\"lat\":33.4012,\"lon\":-86.8123},\"kind\":\"finish\",\"payload\":{\"fleet\":\"01J8Z0E0000000000000000001\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"90d126f21407ebaeb04cf5750e218aad92f7a8d451a24bb21d0a246b532de759\",\"role\":\"overall_pro\",\"seq\":3,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000003\"}"
    },
    {
      "hash": "fcdfc8a416c0687959e2f814a46448b904b8586258f53a2e5671571577841a62",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190004000,\"gps\":null,\"kind\":\"finish.sail\",\"payload\":{\"finish\":\"01J8Z0E0000000000000000003\",\"sail\":\"12345\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"0a62f602a862b127e93907e3ac6bf15215ee43e4135771de2a521a4776932fa8\",\"role\":\"overall_pro\",\"seq\":4,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000004\"}"
    },
    {
      "hash": "d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":null,\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190005000,\"gps\":null,\"kind\":\"note\",\"payload\":{\"text\":\"Mark 2 — hold; wind 10° right\"},\"payload_version\":1,\"person\":null,\"prev_hash\":\"fcdfc8a416c0687959e2f814a46448b904b8586258f53a2e5671571577841a62\",\"role\":\"overall_pro\",\"seq\":5,\"source\":\"tap\",\"ulid\":\"01J8Z0E0000000000000000005\"}"
    },
    {
      "hash": "49e0441befdddcbf81458741bdd8552abe6ada968e26f9e3c8207e244642dc57",
      "canonical": "{\"admission_id\":\"00000000-0000-0000-0000-0000000000a1\",\"corrects_ulid\":\"01J8Z0E0000000000000000002\",\"device_id\":\"01J8Z0D0000000000000000001\",\"device_ts\":1727190006000,\"gps\":null,\"kind\":\"start.time_corrected\",\"payload\":{\"time\":1727190065000},\"payload_version\":1,\"person\":null,\"prev_hash\":\"d7e3b186546cf10b925dc2a629ad37e7b45fcea3a7bd3bb98df106ebdfd923f4\",\"role\":\"overall_pro\",\"seq\":6,\"source\":\"manual\",\"ulid\":\"01J8Z0E0000000000000000006\"}"
    }
  ],
  "expected": {
    "01J8Z0D0000000000000000001": {
      "verdict": "intact"
    }
  }
}
$vector$),
          '{"stored": 6, "hash_matches": 6}'::jsonb,
          'intact: all 6 events stored, each hashing to its recorded hash');

select is((select count(*) from public.event_log), 0::bigint, 'every vector was rolled back, so each went into an empty log');

select * from finish();
rollback;
