// Writes supabase/tests/event_log_vectors_test.sql from fixtures/chain/ (#40 criteria 8 and 9).
//
// The pgTAP test runs inside the database, which cannot read the repo, so every chain vector is
// embedded in it verbatim. test/event_log_vectors_sql_test.dart fails when the committed file is not
// exactly what this writes, so a vector changed under fixtures/chain/ cannot leave the database test
// checking an old copy. After changing a vector:
//
//   dart run scripts/write_event_log_vector_test.dart

import 'dart:convert';
import 'dart:io';

const vectorDir = 'fixtures/chain';
const outputPath = 'supabase/tests/event_log_vectors_test.sql';

/// One chain vector: its file name and its exact text, with LF line endings.
typedef Vector = ({String file, String text});

/// Every vector in [vectorDir], sorted by file name.
List<Vector> readVectors() {
  final files = Directory(vectorDir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  return [
    for (final f in files)
      (file: f.uri.pathSegments.last, text: f.readAsStringSync().replaceAll('\r\n', '\n')),
  ];
}

/// The pgTAP file checking [vectors]: one assertion per vector, and one that every vector was
/// rolled back.
String render(List<Vector> vectors) {
  final out = StringBuffer()
    ..write(r'''
-- GENERATED by scripts/write_event_log_vector_test.dart from fixtures/chain/. Do not edit: change a
-- vector there, then re-run the script. test/event_log_vectors_sql_test.dart fails on any difference.
--
-- pgTAP tests for #40 criteria 8 and 9: #28's chain vectors, inserted into the event log, hash back
-- to each event's recorded hash when SHA-256 is recomputed over the row's stored canonical text. If
-- the canonical column were jsonb, the text read back would be jsonb's own serialisation and no
-- hash would match. Run with `supabase test db` against the local stack; the whole file is one
-- transaction and rolls back.
--
-- Vectors reuse ULIDs across files (an altered or re-linked event keeps its ULID), so each vector
-- goes into an empty log inside a subtransaction that is rolled back once its hashes are read.

begin;
create extension if not exists pgtap with schema extensions;
''')
    ..writeln('select plan(${vectors.length + 1});')
    ..write(r'''

insert into public.club (id, name) values ('00000000-0000-0000-0000-000000000c01', 'Hoover (fixture)');
select public.create_event('00000000-0000-0000-0000-000000000c01', 'Club night', date '2026-09-27',
                           '00000000-0000-0000-0000-000000000e01');

-- Inserts one vector's events as the table owner, the role #48's append_event will run as. Each
-- text goes in as a literal, so a change to the canonical column's type still takes the insert and
-- shows up as a hash that no longer matches. Returns how many rows the log then held, and how many
-- of them hash to the recorded hash of the vector event with the same ULID.
create function pg_temp.check_vector(p_vector jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_event  constant uuid := '00000000-0000-0000-0000-000000000e01';
  v_text   text;
  v_stored bigint;
  v_match  bigint;
begin
  begin
    for v_text in select e ->> 'canonical' from jsonb_array_elements(p_vector -> 'events') e loop
      execute format('insert into public.event_log (event_id, canonical) values (%L, %L)', v_event, v_text);
    end loop;
    select count(*),
           count(*) filter (where encode(sha256(convert_to(l.canonical::text, 'UTF8')), 'hex') = r.hash)
      into v_stored, v_match
      from public.event_log l
      left join (select e ->> 'hash' as hash, (e ->> 'canonical')::jsonb ->> 'ulid' as ulid
                   from jsonb_array_elements(p_vector -> 'events') e) r on r.ulid = l.ulid
     where l.event_id = v_event;
    raise exception using errcode = 'PCV01', message = 'check_vector: roll this vector back';
  exception when sqlstate 'PCV01' then
    null;
  end;
  return jsonb_build_object('stored', v_stored, 'hash_matches', v_match);
end;
$$;
''');
  for (final v in vectors) {
    final name = v.file.replaceAll('.json', '');
    final events = ((jsonDecode(v.text) as Map)['events'] as List).length;
    out
      ..writeln()
      ..writeln('-- $vectorDir/${v.file}')
      ..writeln('select is(pg_temp.check_vector(\$vector\$${v.text}\$vector\$),')
      ..writeln("          '{\"stored\": $events, \"hash_matches\": $events}'::jsonb,")
      ..writeln("          '$name: all $events events stored, each hashing to its recorded hash');");
  }
  out.write(r'''

select is((select count(*) from public.event_log), 0::bigint, 'every vector was rolled back, so each went into an empty log');

select * from finish();
rollback;
''');
  return out.toString();
}

void main() {
  final vectors = readVectors();
  File(outputPath).writeAsStringSync(render(vectors));
  stdout.writeln('wrote $outputPath from ${vectors.length} vectors in $vectorDir');
}
